import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "~/utils/api";
import Image from "next/image";

const Home: NextPage = () => {
  // const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-screen max-h-screen bg-gradient-to-bl from-dark-gray via-slate-800 to-dark-gray">
        <header>
          <nav className="container mx-auto flex items-center justify-between py-5">
            <h5 className="font-vp text-3xl text-gold">Library</h5>
            <ul className="flex flex-row justify-start space-x-20 text-gold">
              <li>
                <Link href="/books" className="text-xl">
                  Books
                </Link>
              </li>
              <li>
                <Link href="/books" className="text-xl">
                  Books
                </Link>
              </li>
              <li>
                <Link href="/books" className="text-xl">
                  Books
                </Link>
              </li>
              <li>
                <Link href="/books" className="text-xl">
                  Books
                </Link>
              </li>
            </ul>
            <h5></h5>
          </nav>
        </header>
        <section className="container relative mx-auto flex h-[90%]  max-w-7xl flex-col items-center justify-center ">
          <div className="z-50 mb-32 w-full">
            <h1 className="z-50 text-left font-vp text-9xl text-gold ">
              Discover
            </h1>
            <h2 className="z-50 ml-24 text-left font-vp text-7xl text-gold ">
              Library of Alexandria
            </h2>
          </div>

          <div className="h-2/2 absolute top-0 right-24 w-2/6   ">
            <Image
              src="/images/sculpture.png"
              alt="Picture of the author"
              width={1000}
              height={1000}
              className="grayscale"
            />
          </div>

          <div className="h-2/2 absolute bottom-0 left-0 w-3/6   ">
            <Image
              src="/images/sculpture2.png"
              alt="Picture of the author"
              width={1000}
              height={1000}
              className="-scale-x-100 transform grayscale"
            />
          </div>

          <div></div>
        </section>
      </main>
    </>
  );
};

export default Home;

// const AuthShowcase: React.FC = () => {
//   const { data: sessionData } = useSession();

//   const { data: secretMessage } = api.example.getSecretMessage.useQuery(
//     undefined, // no input
//     { enabled: sessionData?.user !== undefined }
//   );

//   return (
//     <div className="flex flex-col items-center justify-center gap-4">
//       <p className="text-center text-2xl text-white">
//         {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
//         {secretMessage && <span> - {secretMessage}</span>}
//       </p>
//       <button
//         className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
//         onClick={sessionData ? () => void signOut() : () => void signIn()}
//       >
//         {sessionData ? "Sign out" : "Sign in"}
//       </button>
//     </div>
//   );
// };
